credentials:
  usernames:
    admin:
      email: admin@ratan.ai
      name: Admin Ratan
      password: $2b$12$WBMukQnfYlgJ3nfztGOFpO5mLfhVsuegEDwJLOxfymIAqBxdbHhci # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com